### ISSUE TITLE
Can't run pretrained models (can you add more details in the README?)

### ISSUE THREAD

**Issue by davidefiocco** [nyu-mll/CoLA-baselines#1]
Hi,

Thanks for sharing the code on which your recent paper is based.
I have tried running the code following the instructions on the README: https://github.com/nyu-mll/CoLA-baselines#pretrained-models-and-testing

In the working directory (`acceptability-judgments`), the one containing the README itself, I copied the files
`elmo.emb`
`elmo.pth`
`vocab_100k.tsv`

and I have created also a `data` dir, containing files train, dev, test datafiles obtained with
`cp ./acceptability_corpus/raw/in_domain_train.tsv data/train.tsv`
`cp ./acceptability_corpus/raw/in_domain_dev.tsv data/dev.tsv`
`cp ./acceptability_corpus/raw/in_domain_dev.tsv data/test.tsv`

and then have tried to run with 
`python acceptability/test.py -mf elmo.pth -vf vocab_100k.tsv -ef elmo.emb -d data -g`

Execution fails with:
```
Namespace(crop_pad_length=30, dataset_path='data', embedding_file='elmo.emb', gpu=True, model_file='elmo.pth', preprocess_tokenizer='space', seed=11111, should_not_lowercase=False, should_not_preprocess_data=False, vocab_file='vocab_100k.tsv')
Traceback (most recent call last):
  File "acceptability/test.py", line 61, in <module>
    test(parser.parse_args())
  File "acceptability/test.py", line 15, in test
    dataset = AcceptabilityDataset(args, dataset_path, vocab)
  File "/home/yourstruly/acceptability-judgments/acceptability/modules/dataset.py", line 22, in __init__
    with open(path, 'r') as f:
IsADirectoryError: [Errno 21] Is a directory: 'data'
```
Should `data` not be a directory then? I am likely doing something wrong as I am new to PyTorch, but it seems to me that I am following closely instructions given in the README.  Can you provide any hints on what I am doing wrong? Thanks in advance!

**Comment by alexwarstadt** [comment]
Hi Davide,

Thank you for bringing this to our attention. The command should have read ```python acceptability/test.py -mf elmo.pth -vf vocab_100k.tsv -ef elmo.emb -d data/test.tsv -g```. This has been corrected in the README.

Thanks for your interest!

Alex
